### ISSUE TITLE
push server瞬间下推消息，client异常。

### ISSUE THREAD

**Issue by Technoboy-** [Technoboy-/kafka-push-server#11]
2019-01-08 16:49:26,372 ERROR [com.tt.kafka.client.transport.handler.ClientHandler#exceptionCaught:40] : exceptionCaught
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(4959) + length(4) exceeds writerIndex(4960): PooledUnsafeDirectByteBuf(ridx: 4959, widx: 4960, cap: 8192)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(4959) + length(4) exceeds writerIndex(4960): PooledUnsafeDirectByteBuf(ridx: 4959, widx: 4960, cap: 8192)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1413)
	at io.netty.buffer.AbstractByteBuf.readInt(AbstractByteBuf.java:766)
	at com.tt.kafka.client.transport.codec.PacketDecoder.decode(PacketDecoder.java:52)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	... 16 more
2019-01-08 16:49:26,389 INFO  [KafkaClientTest#onMessage:373] : received push message : partition : 2, value: 357, offset: 170.
2019-01-08 16:49:26,389 ERROR [com.tt.kafka.client.transport.handler.PushMessageHandler#onAcknowledge:41] : ChannelInactiveException, closing the channel
com.tt.kafka.client.transport.exceptions.ChannelInactiveException: channel inactive exception, msg : { Packet [cmd=4, msgId=289439550366072835, bodyLen=0, version=0] }
	at com.tt.kafka.client.transport.NettyConnection.send(NettyConnection.java:96)
	at com.tt.kafka.client.transport.NettyConnection.send(NettyConnection.java:76)
	at com.tt.kafka.client.transport.handler.PushMessageHandler$1.onAcknowledge(PushMessageHandler.java:38)
	at com.tt.kafka.consumer.service.ProxyAcknowledgeMessageListenerService$1.acknowledge(ProxyAcknowledgeMessageListenerService.java:42)
	at KafkaClientTest$9.onMessage(KafkaClientTest.java:374)
	at com.tt.kafka.consumer.service.ProxyAcknowledgeMessageListenerService.onMessage(ProxyAcknowledgeMessageListenerService.java:39)
	at com.tt.kafka.client.transport.handler.PushMessageHandler.handle(PushMessageHandler.java:34)
	at com.tt.kafka.client.transport.handler.MessageDispatcher.dispatch(MessageDispatcher.java:27)
	at com.tt.kafka.client.transport.handler.ClientHandler.channelRead(ClientHandler.java:36)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)
2019-01-08 16:49:30,271 INFO  [com.tt.kafka.client.transport.NettyClient#doConnect:112] : connect to server : /172.16.136.76:10669 success

**Comment by Technoboy-** [comment]
协议错误。已改正。
